version: '3'
services:
  db:
    image: mysql:5.7.22
    container_name: shogi-db
    environment:
      - MYSQL_DATABASE=shogi-db
      - MYSQL_ROOT_PASSWORD=1234hot5
      - MYSQL_USER=root
      - MYSQL_PASSWORD=1234hot5
    volumes:
      - ./data:/docker-entrypoint-initdb.d
    ports:
      - "3306:3306"